line-length = 110
indent-width = 4
target-version = "py310"

[format]
quote-style = "double"
indent-style = "tab"


[lint]
select = [
  "F",
  "E",
  "W",
  "I",
  "UP",
  "B",
  # "RUF",
  # "FA",
  # "TCH",
  # "C90",
  # "RET",
  # "SIM",
]
ignore = [
  "UP015",  # Unnecessary open mode parameters
  "SIM108", # Use ternary operator {contents} instead of if-else-block
  "F821",   # Undefined name, cause of DF.Literal
  "F722",   # syntax error in forward type annotation, cause of DF.Literal
  "E501",   # line too long, cause hooks.py
  "W191",   # indentation contains tabs, cause when the world zigs, we zag
  "B023",   # function doesn't bind loop variable - will have last iteration's value

  # "B017",   # assertRaises(Exception) - should be more specific
  # "B018",   # useless expression, not assigned to anything
  # "B904",   # raise inside except without from
  # "E101",   # indentation contains mixed spaces and tabs
  # "E402",   # module level import not at top of file
  # "E741",   # ambiguous variable name
  # "F401",   # "unused" imports
  # "F403",   # can't detect undefined names from * import
  # "F405",   # can't detect undefined names from * import
  # "RUF001", # string contains ambiguous unicode character
  # "UP032",  # Use f-string instead of `format` call (translations)
  # "UP030",  # Use implicit references for positional format fields (translations)
]


[lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 8
max-complexity = 8
